# This is a basic workflow to help you get started with Actions

name: Deploy Pushed Committed changes to staging server

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: 
      - staging

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.1.0
      with:
        fetch-depth: 2
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@3.1.1
      with:
        ftp-server: ${{ secrets.IM_TRINC_FTP_SERVERD }}
        ftp-username: ${{ secrets.IM_TRINC_FTP_USERNAME }}
        ftp-password: ${{ secrets.IM_TRINC_FTP_PASSWORD }}
        local-dir: staging.thunderroadinc.com/inventory/
